port: 8888
socks-port: 8889
redir-port: 9090
allow-lan: true
mode: Rule
log-level: info
external-controller: '127.0.0.1:6170'
secret: ''

Proxy:
  - name: Shadowsocks
    type: socks5
    server: 127.0.0.1
    port: 1080
Proxy Group:
  - name: Proxy
    type: select
    proxies:
      - Shadowsocks
Rule:
  - 'MATCH,DIRECT'
