image: Visual Studio 2019

init:
  - cmd: set PATH=C:\Python38-x64;C:\Python38-x64\Scripts;%PATH%

environment:
  maxmind_key:
    secure: nSZU0wd6GZbqxuIn7emmkYZhJuFTZO2iu0MLGGEK4C0=

platform:
  - Any CPU

configuration:
  - Release

before_build:
  - cmd: nuget restore
  - cmd: cd build && pip install requests && python download_assets.py %maxmind_key%

after_build:
  - cmd: makensis installer.nsi

artifacts:
  - path: build/ClansSetup.exe

deploy:
  release: $(APPVEYOR_REPO_TAG_NAME)
  description: $(APPVEYOR_REPO_TAG_NAME)
  provider: GitHub
  auth_token:
    secure: Qn6+z/GoGysZOhbEgFgbop0yDk9ZZ18jX8snzUvM96a5wX0CsR1OgFOmitARUqFc
  artifact: build/ClansSetup.exe
  force_update: true
  on:
    branch: master
    APPVEYOR_REPO_TAG: true
