image: Visual Studio 2019

init:
  - cmd: set PATH=C:\Python38-x64;C:\Python38-x64\Scripts;%PATH%

environment:
  maxmind_key:
    secure: nSZU0wd6GZbqxuIn7emmkYZhJuFTZO2iu0MLGGEK4C0=

platform:
  - Any CPU

configuration:
  - Release

install:
  - ps: |
      Invoke-WebRequest https://raw.githubusercontent.com/appveyor/build-images/master/scripts/Windows/install_nsis.ps1 -OutFile "build\install_nsis.ps1"
      build\install_nsis.ps1

before_build:
  - cmd: nuget restore
  - cmd: cd build && pip install requests && python download_assets.py %maxmind_key%

after_build:
  - cmd: cd build && makensis installer.nsi

artifacts:
  - path: build/*.exe
